name: "Build binaries"
on:
    push: 
        branches: ["master"]
jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
              goos: ["darwin", "linux"]
              goarch: ["amd64", "arm64"]
        steps:
        - name: Check out repository code
          uses: actions/checkout@v4

        - name: Set up Go
          uses: actions/setup-go@v5
          with:
            go-version: '1.24'

        - name: Build for ${{ matrix.goos }}-${{ matrix.goarch }}
          run: |
            mkdir -p dist
            go build -o dist/mango-${{ matrix.goos }}-${{ matrix.goarch }}

        - name: Publish artifact
          uses: actions/upload-artifact@v4
          with:
            name: mango-${{ matrix.goos }}-${{ matrix.goarch }}
            path: dist/mango-${{ matrix.goos }}-${{ matrix.goarch }}